version: '3.8'

services:
  products:
    build: ./products
    ports:
      - "3001:3001"

  orders:
    build: ./orders
    ports:
      - "3002:3002"
    depends_on:
      - redis
      - db
      - products

  payments:
    build: ./payments
    ports:
      - "3003:3003"
    depends_on:
      - orders

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"